httpProxy: '${http_proxy:-}'

httpsProxy: '${https_proxy:-}'

nodeLinker: node-modules

plugins:
    - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmRegistryServer: 'https://registry.npmmirror.com'
npmAuditIgnoreAdvisories:
    # Ignore advisories for xlsx package. This package is depended on by a third-party library rowsncolumns (docs)
    # and hasn't gotten any priority to change.
    - 1108110
    - 1108111

compressionLevel: mixed
